require 'set'
require 'neo4j/extensions/aggregate/aggregator'
require 'neo4j/extensions/aggregate/group_enum'
require 'neo4j/extensions/aggregate/group_node'
require 'neo4j/extensions/aggregate/property_enum'
require 'neo4j/extensions/aggregate/aggregate_node_mixin'
require 'neo4j/extensions/aggregate/aggregate_node'
require 'neo4j/extensions/aggregate/ext/node_mixin'

require 'neo4j/extensions/aggregate/aggregator_each'
require 'neo4j/extensions/aggregate/group_each_node'
require 'neo4j/extensions/aggregate/aggregate_each_node_mixin'
require 'neo4j/extensions/aggregate/aggregate_each_node'
