source 'http://rubygems.org'

gem 'neo4j', :path => "../.."

gem 'neo4j-advanced', '1.8.RC1' # you might have to change this so that it is the same version as neo4j-community
gem 'neo4j-enterprise', '1.8.RC1'
