name: E2E Test

on:
  push:
    branches: [ '11' ]
  pull_request:
    branches: [ '11' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby == 'ruby' }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ruby: [ jruby-9.4.5.0, ruby-3.1.4 ]
        neo4j: [ 5.15.0 ]
        # active_model: [ 7.0.8, 7.1.2 ]
        include:
          - ruby: ruby-3.2.2
            neo4j: 5.15.0
            active_model: 7.1.2
    env:
      # NEO4J_VERSION: ${{ matrix.neo4j }}
      # ACTIVE_MODEL_VERSION: ${{ matrix.active_model }}
      JRUBY_OPTS: --debug -J-Xmx1280m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF
    steps:
      - name: Start neo4j
        run: docker run --name neo4j --env NEO4J_AUTH=neo4j/password --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes --env NEO4J_dbms_directories_import= -p7687:7472 -p7474:7474 -v `pwd`/tmp:/var/lib/neo4j/import --rm neo4j:${{ matrix.neo4j }}-enterprise &

      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup test rails app
        run: ./e2e_tests/setup.sh

      - name: log
        run: printf "$SHA"

      - name: log-two
        run: echo "${{ env.SHA }}"

      - name: Wait for neo4j
        run: while [ $((curl localhost:7474/ > /dev/null 2>&1); echo $?) -ne 0 ]; do sleep 1; done

      # - name: Run tests
      #   run: bundle exec rspec e2e_tests/
